   version: "3.8"
   services:
       app:
           build:
               context: .
               dockerfile: Dockerfile
           container_name: news-app-container
           restart: unless-stopped
           ports:
               - "8000:8000"
           volumes:
               - .:/var/www/html
           networks:
               - news-network
           depends_on:
               - mysql
               - redis

       mysql:
           image: mysql:8.0
           container_name: news-mysql
           restart: unless-stopped
           ports:
               - "3306:3306"
           environment:
               MYSQL_ROOT_PASSWORD: root
               MYSQL_DATABASE: news_aggregator
               MYSQL_USER: laravel
               MYSQL_PASSWORD: laravel
           volumes:
               - mysql_data:/var/lib/mysql
           networks:
               - news-network

       redis:
           image: redis:7-alpine
           container_name: news-redis
           restart: unless-stopped
           ports:
               - "6379:6379"
           networks:
               - news-network

   networks:
       news-network:
           driver: bridge

   volumes:
       mysql_data:
           driver: local